### ISSUE TITLE
[🐛 Bug]: failed to install bedrockpy

### ISSUE THREAD

**Issue by thetomato0** [bedrock-ws/bedrockpy#6]
**Describe the bug**
when i use the command: pip install bedrockpy it gives an error saying:

ERROR: Ignored the following yanked versions: 0.0.0, 0.1.0, 0.1.1, 0.1.1.post1
ERROR: Could not find a version that satisfies the requirement bedrockpy (from versions: 1.0.0a0, 1.0.0a0.post1)
ERROR: No matching distribution found for bedrockpy

**Additional context**
it seams that the error comes from having spaces in setup.py but im not sure

**Comment by phoenixr-codes** [comment]
bedrockpy only has pre-releases or yanked releases on PyPI. pip only respects stable non-yanked releases. To install bedrockpy use one of the following methods:

- **Supply the `--pre` option**: `pip install --pre bedrockpy`, this makes pip respect pre releases as well
- **Specify the version explicitly**: `pip install bedrockpy==1.0.0a0.post1`
- **Download latest from git**: `pip install git+https://github.com/bedrock-ws/bedrockpy.git`

**Comment by phoenixr-codes** [comment]
Now obsolete with major release (https://github.com/bedrock-ws/bedrockpy/commit/20110fc8016baca7e51cc9e9e66078a0895c7827)
